use_frameworks!

target 'AjmdPlayerSDK_Example' do
  pod 'AjmdPlayerSDK', :path => '../'

  target 'AjmdPlayerSDK_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
